JewleryStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView, name='home'),
    path('masteruser/', include('masteruser.urls',namespace = 'masteruser')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('commonuser/', include('commonuser.urls',namespace = 'commonuser')),
    path('jewlery/', include('jewlery.urls',namespace = 'jewlery')),
    path('order/', include('order.urls',namespace = 'order')),
    path('company/', include('company.urls',namespace = 'company')),
    path('',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

commonuser/urls.py
from django.urls import include, path
from commonuser.views import (TwoMinWaitView, CommonUserSignupView, UserConfirmView,
                            CustomerListView, JewlerListView, JewlerReqListView,
                            JewlerConfirmView, JewlerDenyView, CommonUserProfileView,
                            CommonUserUpdateView)

# handmade
app_name ='commonuser'
urlpatterns = [
    path('signup/',CommonUserSignupView, name='signup'),
    path('confirm/',UserConfirmView, name='confirm'),
    path('wait/',TwoMinWaitView, name='twominwait'),
    path('customerlist/',CustomerListView, name='customerlist'),
    path('jewlerlist/',JewlerListView, name='jewlerlist'),
    path('jewlerreqlist/',JewlerReqListView, name='jewlerreqlist'),
    path('jewler-confirm/<int:pk>',JewlerConfirmView, name='jewlerconfirm'),
    path('jewler-deny/<int:pk>',JewlerDenyView, name='jewlerdeny'),
    path('profile/<slug:slug>',CommonUserProfileView, name='profile'),
    path('update/<slug:slug>',CommonUserUpdateView, name='update'),
]

company/urls.py
from django.urls import include, path
from company.views import (ContactUsView, AboutUsView, ContactUsListView,
                            ContactUsDeleteView, FAQsView, TermandConditionsView)

app_name ='company'
urlpatterns = [
    path('about-us/',AboutUsView, name = 'aboutus'),
    path('faqs/', FAQsView, name = 'faqs'),
    path('terms-and-conditions/',TermandConditionsView, name = 'termsandconditions'),
    path('contact-us/',ContactUsView, name = 'contactus'),
    path('contact-us-list/',ContactUsListView, name = 'contactuslist'),
    path('contact-us-delete/<int:pk>',ContactUsDeleteView, name = 'contact-us-delete'),

]

jewlery/urls.py
from django.urls import include, path
from jewlery.views import (JewleryCreateView,ConfirmedJewleryListView, JewleryDetailView,
                            JewleryUpdateView, JewleryPictureUpdateView, JewleryPictureAddView,
                            UnConfirmedJewleryListView, JewleryPublicListView, JewleryDeleteView,
                            JewleryPublicDetailView, CreateUnitView)

app_name = 'jewlery'
urlpatterns = [
    path('create-unit/', CreateUnitView, name='createunit'),
    path('create/', JewleryCreateView, name='create'),
    path('confirmed-list/', ConfirmedJewleryListView, name='confirmedlist'),
    path('unconfirmed-list/', UnConfirmedJewleryListView, name='unconfirmedlist'),
    path('public-list/', JewleryPublicListView, name='publiclist'),
    path('public-detail/<int:pk>/', JewleryPublicDetailView, name='publicdetail'),
    path('detail/<int:pk>/', JewleryDetailView, name='detail'),
    path('update/<int:pk>/', JewleryUpdateView, name='update'),
    path('delete/<int:pk>/', JewleryDeleteView, name='delete'),
    path('picture-update/<int:pk>/', JewleryPictureUpdateView, name='pictureupdate'),
    path('picture-add/<int:pk>/', JewleryPictureAddView, name='pictureadd'),

]

masteruser/urls.py
from django.urls import include, path
from masteruser.views import (MasterUserSignupView, MasterUserListView,
                            MasterUserDeleteView, MasterUserDashboardView)

app_name = 'masteruser'
urlpatterns = [
    path('signup/', MasterUserSignupView, name='signup'),
    path('list/', MasterUserListView.as_view(), name='list'),
    path('delete/<slug:slug>', MasterUserDeleteView, name='delete'),
    path('dashboard/<slug:slug>', MasterUserDashboardView, name='dashboard'),


]

order/urls.py
from django.urls import include, path
from order.views import (OrderingView,OrderSuccessView, OrderListForJewleryView,
                        CheckedOrderListView, UnCheckedOrderListView, OrderListForCommonUserView,
                        CheckOrderView, UnCheckOrderView, OrderUpdateView, DeliverOrderView,
                        DeliveredOrderListView, UnDeliverOrderView, DeleteOrderView)

app_name = 'order'
urlpatterns = [
    path('ordering/<int:pk>/', OrderingView, name='ordering'),
    path('update/<int:pk>/', OrderUpdateView, name='update'),
    path('success/', OrderSuccessView, name='success'),
    path('list-for-jewlery/<int:pk>', OrderListForJewleryView, name='listforjewlery'),
    path('list-for-user/<slug:slug>', OrderListForCommonUserView, name='listforuser'),
    path('checked-list/', CheckedOrderListView, name='checkedlist'),
    path('unchecked-list/', UnCheckedOrderListView, name='uncheckedlist'),
    path('check/<int:pk>/', CheckOrderView, name='check'),
    path('uncheck/<int:pk>/', UnCheckOrderView, name='uncheck'),
    path('deliver/<int:pk>/', DeliverOrderView, name='deliver'),
    path('deliver/<int:pk>/', DeleteOrderView, name='delete'),
    path('undeliver/<int:pk>/', UnDeliverOrderView, name='undeliver'),
    path('delivered-list/', DeliveredOrderListView, name='deliveredlist'),


]

masteruser/models.py
from django.db import models
from django.conf import settings

class MasterUserModel(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE,
                               related_name='masterusers', primary_key = True)
    logs = models.TextField(null = True, blank = True)


    def __str__(self):
        return self.user.username

masteruser/forms.py
from django import forms
from masteruser.models import MasterUserModel
from django.core import validators


class MasterUserForm(forms.ModelForm):
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    class Meta:
        model = MasterUserModel
        fields = ('logs',)

masteruser/views.py
from django.shortcuts import render
from django.urls import reverse
from django.utils.text import slugify
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.utils import timezone
from django.conf import settings
from django.utils.decorators import method_decorator

#handmade
from accounts.decorators import superuser_required
from masteruser.decorators import masteruser_required
from accounts.models import UserModel
from masteruser.models import MasterUserModel
from accounts.forms import UserForm
from masteruser.forms import MasterUserForm

# Create your views here.

@login_required
@superuser_required
def MasterUserSignupView(request):
    if request.method == 'POST':

        user_form = UserForm(data = request.POST)
        masteruser_form = MasterUserForm(data = request.POST)

        if user_form.is_valid() and masteruser_form.is_valid():

             user = user_form.save()
             user.is_masteruser = True
             user.save()
             masteruser = masteruser_form.save(commit=False)
             masteruser.user = user
             masteruser.save()
             ###
             return HttpResponseRedirect(reverse('home'))
        else:
             print(user_form.errors,masteruser_form.errors)


    else:
        user_form = UserForm()
        masteruser_form = MasterUserForm()

    return render(request,'masteruser/signup.html',
                          {'user_form':user_form,
                           'masteruser_form':masteruser_form,})


@method_decorator([login_required, superuser_required], name='dispatch')
class MasterUserListView(ListView):
    model = MasterUserModel
    context_object_name = 'masterusers'
    template_name = 'masteruser/list.html'


@login_required
@superuser_required
def MasterUserDeleteView(request,slug):
    if request.user.is_superuser:
        user = get_object_or_404(UserModel,slug = slug)
        masteruser = get_object_or_404(MasterUserModel,user = user)
        masteruser.delete()
        user.delete()
        return HttpResponseRedirect(reverse('accounts:dashboard',kwargs={'slug':request.user.slug}))
    else:
        return HttpResponseRedirect(reverse('accounts:login'))


@login_required
@masteruser_required
def MasterUserDashboardView(request,slug):
    return render(request,'masteruser/dashboard.html')

masteruser/templates/masteruser/dashboard.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<h1 style="text-shadow: 0 0 30px black" class="uk-text-center goldC-text fHarmattan">داشبورد</h1>
<br><br>
<div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>
  <div class="uk-width-1-6 uk-width-1-4@m">

  </div>
      <div class="uk-width-2-3 uk-width-1-2@m ">
<a href="{% url 'jewlery:createunit' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">تعیین فی</a>
<a href="{% url 'jewlery:create' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">ایجاد محصول</a>
<a href="{% url 'jewlery:confirmedlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست محصولات تایید شده</a>
<a href="{% url 'jewlery:unconfirmedlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست محصولات تایید نشده</a>
<a href="{% url 'order:uncheckedlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">سفارشات چک نشده</a>
<a href="{% url 'order:checkedlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">سفارشان چک شده</a>
<a href="{% url 'order:deliveredlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">سفارشات تحویل داده شده</a>
<a href="{% url 'commonuser:customerlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست مشتریان</a>
<a href="{% url 'commonuser:jewlerreqlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست طلا فروشان در انتظار تایید</a>
<a href="{% url 'commonuser:jewlerlist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست طلا فروشان تایید شده</a>
<a href="{% url 'company:contactuslist' %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست تماس با ما</a>

</div>
<div class="uk-width-1-6 uk-width-1-4@m">

</div>
</div>
<br><br><br><br>
    {% endblock %}

masteruser/templates/masteruser/list.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}
{% block body_block %}
    {% for masteruser in masterusers %}
    {{masteruser.user.username}}
    delete with slug
    <a href="{% url 'masteruser:delete' masteruser.user.slug %}">delete ZERT</a><br>
    ------------------------------------------------------ <br>
    {% endfor %}


    {% endblock %}

masteruser/templates/masteruser/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>masteruser signup</h1>
    <form method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ masteruser_form.as_p }}
      <input type="submit" name="" value="submit">
    </form>
  </body>
</html>