JewleryStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView, name='home'),
    path('masteruser/', include('masteruser.urls',namespace = 'masteruser')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('commonuser/', include('commonuser.urls',namespace = 'commonuser')),
    path('jewlery/', include('jewlery.urls',namespace = 'jewlery')),
    path('order/', include('order.urls',namespace = 'order')),
    path('company/', include('company.urls',namespace = 'company')),
    path('',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from accounts.forms import UserLoginForm
from accounts.views import (SuperUserDashboardView, PasswordChangeView,
                        ForgotPasswordView, WaitView, WrongPhoneNumberView)

# handmade
app_name ='accounts'
urlpatterns = [
    path('auth/',auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=UserLoginForm), name='login'),
    path('dashboard/<slug:slug>/',SuperUserDashboardView, name='dashboard'),
    path('wait/',WaitView, name='wait'),
    path('wrongphonenumber/',WrongPhoneNumberView, name='wrongphonenumber'),
    path('password-change/<slug:slug>/',PasswordChangeView, name='passwordchange'),
    path('password-forget/',ForgotPasswordView, name='passwordforget'),
]

commonuser/urls.py
from django.urls import include, path
from commonuser.views import (TwoMinWaitView, CommonUserSignupView, UserConfirmView,
                            CustomerListView, JewlerListView, JewlerReqListView,
                            JewlerConfirmView, JewlerDenyView, CommonUserProfileView,
                            CommonUserUpdateView)

# handmade
app_name ='commonuser'
urlpatterns = [
    path('signup/',CommonUserSignupView, name='signup'),
    path('confirm/',UserConfirmView, name='confirm'),
    path('wait/',TwoMinWaitView, name='twominwait'),
    path('customerlist/',CustomerListView, name='customerlist'),
    path('jewlerlist/',JewlerListView, name='jewlerlist'),
    path('jewlerreqlist/',JewlerReqListView, name='jewlerreqlist'),
    path('jewler-confirm/<int:pk>',JewlerConfirmView, name='jewlerconfirm'),
    path('jewler-deny/<int:pk>',JewlerDenyView, name='jewlerdeny'),
    path('profile/<slug:slug>',CommonUserProfileView, name='profile'),
    path('update/<slug:slug>',CommonUserUpdateView, name='update'),
]

company/urls.py
from django.urls import include, path
from company.views import (ContactUsView, AboutUsView, ContactUsListView,
                            ContactUsDeleteView, FAQsView, TermandConditionsView)

app_name ='company'
urlpatterns = [
    path('about-us/',AboutUsView, name = 'aboutus'),
    path('faqs/', FAQsView, name = 'faqs'),
    path('terms-and-conditions/',TermandConditionsView, name = 'termsandconditions'),
    path('contact-us/',ContactUsView, name = 'contactus'),
    path('contact-us-list/',ContactUsListView, name = 'contactuslist'),
    path('contact-us-delete/<int:pk>',ContactUsDeleteView, name = 'contact-us-delete'),

]

order/urls.py
from django.urls import include, path
from order.views import (OrderingView,OrderSuccessView, OrderListForJewleryView,
                        CheckedOrderListView, UnCheckedOrderListView, OrderListForCommonUserView,
                        CheckOrderView, UnCheckOrderView, OrderUpdateView, DeliverOrderView,
                        DeliveredOrderListView, UnDeliverOrderView, DeleteOrderView)

app_name = 'order'
urlpatterns = [
    path('ordering/<int:pk>/', OrderingView, name='ordering'),
    path('update/<int:pk>/', OrderUpdateView, name='update'),
    path('success/', OrderSuccessView, name='success'),
    path('list-for-jewlery/<int:pk>', OrderListForJewleryView, name='listforjewlery'),
    path('list-for-user/<slug:slug>', OrderListForCommonUserView, name='listforuser'),
    path('checked-list/', CheckedOrderListView, name='checkedlist'),
    path('unchecked-list/', UnCheckedOrderListView, name='uncheckedlist'),
    path('check/<int:pk>/', CheckOrderView, name='check'),
    path('uncheck/<int:pk>/', UnCheckOrderView, name='uncheck'),
    path('deliver/<int:pk>/', DeliverOrderView, name='deliver'),
    path('deliver/<int:pk>/', DeleteOrderView, name='delete'),
    path('undeliver/<int:pk>/', UnDeliverOrderView, name='undeliver'),
    path('delivered-list/', DeliveredOrderListView, name='deliveredlist'),


]

commonuser/models.py
from django.db import models
from django.conf import settings

class CommonUserModel(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE,
                               related_name='commonusers', primary_key = True)
    address = models.TextField(null = True, blank = True)
    is_jewler_request = models.BooleanField('Jewler Request', default = False)
    is_jewler = models.BooleanField('Jewler Status', default = False)

    def __str__(self):
        return self.user.username

commonuser/forms.py
from django import forms
from commonuser.models import CommonUserModel
from django.core import validators

class CommonUserForm(forms.ModelForm):
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    class Meta:
        model = CommonUserModel
        fields = ('is_jewler_request','address')
        widgets = {
            'address': forms.Textarea(attrs={'class':'uk-textarea fHarmattan','rows':'3','placeholder':'آدرس','id':'text','style':'display:none;color:#c7a046;background-color:#212121;'}),
            'is_jewler_request': forms.CheckboxInput(attrs={'class': 'uk-checkbox','id':'is_jewler_request','id':'myCheck', 'onclick':'myFunction()'}),
        }


class ConfirmationForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-input fHarmattan','placeholder':'کد ارسالی به شماره تلفن','id': 'code',}))
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

commonuser/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
import jdatetime
import datetime
import random
from django.conf import settings
from django.utils import timezone

#handmade
from accounts.models import UserModel
from accounts.forms import UserForm, UserUpdateForm
from commonuser.models import CommonUserModel
from commonuser.forms import CommonUserForm, ConfirmationForm
from masteruser.decorators import masteruser_required
from commonuser.decorators import commonuser_required

# Create your views here.
def CommonUserSignupView(request):
    #api = KavenegarAPI(settings.KAVENEGAR_API_KEY)
    try:
        last_retry_str = request.session['last_retry']
        retries = request.session['retries']
        last_retry = datetime.datetime.strptime(last_retry_str,"%Y-%m-%d %H:%M:%S")
    except:
        last_retry = datetime.datetime.now()
    now = datetime.datetime.now()
    if now >= last_retry or retries != 2:
        if request.method == 'POST':

            user_form = UserForm(data = request.POST)
            commonuser_form = CommonUserForm(data = request.POST)

            if user_form.is_valid() and commonuser_form.is_valid():
                 request.session['name'] =  user_form.cleaned_data.get('name')
                 request.session['password1'] =  user_form.cleaned_data.get('password1')
                 request.session['username'] = user_form.cleaned_data.get('username')
                 request.session['address'] = commonuser_form.cleaned_data.get('address')
                 request.session['is_jewler_request'] = commonuser_form.cleaned_data.get('is_jewler_request')
                 #### generating code
                 var = '1234567890'
                 random_code=''
                 for i in range(5):
                     c = random.choice(var)
                     random_code += c
                 code = random_code
                 ######### send code to commonuser
                 '''
                 params = {
                 'sender': settings.KAVENEGAR_PHONE_NUMBER,
                 'receptor': phone_number,
                 'message' : 'سامانه ورزش کن \n' +'کد فعالسازی شما' +  ' :' + code
                 }
                 '''
                 try:
                     #response = api.sms_send(params)
                     print(code)
                     request.session['code'] =  code
                     now = datetime.datetime.now() + datetime.timedelta(minutes=2)
                     str_now = str(now.year)+'-'+str(now.month)+'-'+str(now.day)+' '+str(now.hour)+':'+str(now.minute)+':'+str(now.second)
                     request.session['last_retry'] = str_now
                     try:
                         if request.session['retries'] == 1:
                             request.session['retries'] = 2
                     except:
                         request.session['retries'] = 1


                 except:
                     return HttpResponseRedirect(reverse('accounts:wrongphonenumber'))


                 return HttpResponseRedirect(reverse('commonuser:confirm'))
            else:
                print(user_form.errors,commonuser_form.errors)


        else:
            user_form = UserForm()
            commonuser_form = CommonUserForm()

        return render(request,'commonuser/signup.html',
                              {'user_form':user_form,
                               'commonuser_form':commonuser_form})
    else:
        return HttpResponseRedirect(reverse('commonuser:twominwait'))



def UserConfirmView(request):
    name = request.session['name']
    password1 = request.session['password1']
    username = request.session['username']
    address = request.session['address']
    code = request.session['code']
    is_jewler_request = request.session['is_jewler_request']
    if is_jewler_request:
        is_jewler_request = True
    else:
        is_jewler_request = False
    if request.method == 'POST':

        confirmation_form = ConfirmationForm(data = request.POST)

        if confirmation_form.is_valid():
            confirmation_code = confirmation_form.cleaned_data.get('code')
            if confirmation_code == code:
                user = UserModel.objects.create(username=username, password=password1,
                                            name = name)
                user.is_active = True
                user.is_commonuser = True
                # hashing password
                user.set_password(user.password)
                user.save()
                print(address,'2')
                commonuser = CommonUserModel.objects.create(user=user, address=address, is_jewler_request = is_jewler_request)
                commonuser.save()
                return HttpResponseRedirect(reverse('accounts:login'))
        else:
            print(confirmation_form.errors)


    else:
        confirmation_form = ConfirmationForm()
    return render(request,'commonuser/confirm.html',
                          {'confirmation_form':confirmation_form,'phone_number':username})
#    except:
#        return HttpResponseRedirect(reverse('commonuser:signup'))


def TwoMinWaitView(request):
    return render(request,'accounts/wait.html')

@login_required
@masteruser_required
def CustomerListView(request):
    customers = CommonUserModel.objects.filter(is_jewler_request = False)
    return render (request,'commonuser/customerlist.html',{'customers':customers})


@login_required
@masteruser_required
def JewlerReqListView(request):
    jewlers = CommonUserModel.objects.filter(is_jewler_request = True, is_jewler = False)
    return render (request,'commonuser/jewlerreq.html',{'jewlers':jewlers})


@login_required
@masteruser_required
def JewlerListView(request):
    jewlers = CommonUserModel.objects.filter(is_jewler = True)
    return render (request,'commonuser/jewlers.html',{'jewlers':jewlers})


@login_required
@masteruser_required
def JewlerConfirmView(request,pk):
    jewler = get_object_or_404(CommonUserModel,pk=pk)
    jewler.is_jewler = True
    jewler.is_jewler_request = False
    jewler.save()
    return HttpResponseRedirect(reverse('commonuser:jewlerreqlist'))


@login_required
@masteruser_required
def JewlerDenyView(request,pk):
    jewler = get_object_or_404(CommonUserModel,pk=pk)
    jewler.is_jewler_request = False
    jewler.save()
    return HttpResponseRedirect(reverse('commonuser:jewlerreqlist'))


@login_required
@commonuser_required
def CommonUserProfileView(request,slug):
    commonuser_user = get_object_or_404(UserModel,slug=slug)
    commonuser = get_object_or_404(CommonUserModel,user=commonuser_user)
    return render (request,'commonuser/profile.html',{'commonuser':commonuser})


@login_required
@commonuser_required
def CommonUserUpdateView(request,slug):
    commonuser_user = get_object_or_404(UserModel,slug = slug)
    commonuser = get_object_or_404(CommonUserModel,user=commonuser_user)
    if request.user == commonuser_user :
        user_update_form = UserUpdateForm(request.POST or None, instance = commonuser_user)
        commonuser_update_form = CommonUserForm(request.POST or None, instance = commonuser)
        if user_update_form.is_valid() and commonuser_update_form.is_valid():
            user_update_form.save()
            commonuser_update_form.save()
            return HttpResponseRedirect(reverse('commonuser:profile',
                                        kwargs={'slug':commonuser_user.slug}))
        return render(request,'commonuser/update.html',
                              {'user_form':user_update_form,'commonuser_form':commonuser_update_form})
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

commonuser/templates/commonuser/confirm.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
ورود | شعله خیز
</title>
{% endblock %}
{% block body_block %}
<br>
<div class="uk-grid-match uk-grid-small uk-text-center " uk-grid>
  <div class="uk-width-1-6 uk-width-1-4@m">

  </div>
      <div class="uk-width-2-3 uk-width-1-2@m uk-block ">
<div class="uk-card uk-card-hover uk-card-body darkgreyC ">
    <h3 style="font-size:30px;" class="goldC-text uk-card-title uk-align-center fHarmattan">کد تایید</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>
{{confirmation_form.Hfield}}
<div class="uk-width-1-2@m fHarmattan uk-text-center goldC-text">
کد ارسالی به شماره همره
{{phone_number}}
را وارد کنید.
</div>
      <div class="uk-width-1-1@m">
      {{confirmation_form.code}}
      </div>



              {% if confirmation_form.errors %}
                  <div class="uk-width-1-1">
              <p  class="fHarmattan goldC-text">مشکلی پیش آمد. لطفا دوباره سعی کنید</p>
              </div>
              {% endif %}

      </div>
      <br>
      <button style="margin-top:20px;" class="uk-button uk-button-primary fHarmattan goldC darkgreyC-text" type="submit">تایید
    </button><br><br>
    </form>
</div>
<div class="uk-width-1-6 uk-width-1-4@m">

</div>
</div>
</div>
<br><br><br>

{% endblock %}

commonuser/templates/commonuser/customerlist.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<br>
<h3 style="font-size:30px;" class="goldC-text uk-text-center fHarmattan uk-text-large">لیست مشتریان عادی</h3>
<br>
<div style="padding:4%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>

  {% for customer in customers %}
  <div class="uk-width-1-1 uk-width-1-2@s uk-block">
<div  class="uk-card uk-card-default uk-card-body darkgreyC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large" uk-grid>
  <div class="uk-width-1-2 uk-text-left goldC-text" >شماره تماس</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{customer.user.username}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >نام</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{customer.user.name}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >درخواست طلا فروشی</div><div class="uk-width-1-2 uk-text-right whiteC-text">{% if customer.is_customer_request %}بله{% else %} خیر{% endif %}</div>

<div class="uk-width-2-5 uk-text-left goldC-text" >آدرس</div><div class="uk-width-3-5 uk-text-right whiteC-text">{{customer.address}}</div>

</div>
</div>
</div>
  {% endfor %}

    {% endblock %}

commonuser/templates/commonuser/jewlerreq.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<br>
<h3 style="font-size:30px;" class="goldC-text uk-text-center fHarmattan uk-text-large">لیست طلا فروشان در انتظار تایید</h3>
<br>
<div style="padding:4%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>

  {% for jewler in jewlers %}
  <div class="uk-width-1-1 uk-width-1-2@s uk-block">
<div  class="uk-card uk-card-default uk-card-body darkgreyC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large" uk-grid>
  <div class="uk-width-1-2 uk-text-left goldC-text" >شماره تماس</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{jewler.user.username}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >نام</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{jewler.user.name}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >در انتظار تایید </div><div class="uk-width-1-2 uk-text-right whiteC-text">{% if jewler.is_jewler_request %}بله{% else %} خیر{% endif %}</div>

<div class="uk-width-2-5 uk-text-left goldC-text" >آدرس</div><div class="uk-width-3-5 uk-text-right whiteC-text">{{jewler.address}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" ><a href="{% url 'commonuser:jewlerconfirm' jewler.pk %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">تایید درخواست</a></div>
  <div class="uk-width-1-2 uk-text-right whiteC-text"><a href="{% url 'commonuser:jewlerdeny' jewler.pk %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">رد درخواست</a></div>

      </div>
</div>
</div>
  {% endfor %}

    {% endblock %}

commonuser/templates/commonuser/jewlers.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<br>
<h3 style="font-size:30px;" class="goldC-text uk-text-center fHarmattan uk-text-large">لیست طلا فروشان تایید شده</h3>
<br>
<div style="padding:4%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>

  {% for jewler in jewlers %}
  <div class="uk-width-1-1 uk-width-1-2@s uk-block">
<div  class="uk-card uk-card-default uk-card-body darkgreyC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large" uk-grid>
  <div class="uk-width-1-2 uk-text-left goldC-text" >شماره تماس</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{jewler.user.username}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >نام</div><div class="uk-width-1-2 uk-text-right whiteC-text">{{jewler.user.name}}</div>
  <div class="uk-width-1-2 uk-text-left goldC-text" >طلا فروش تایید شده</div><div class="uk-width-1-2 uk-text-right whiteC-text">{% if jewler.is_jewler %}بله{% else %} خیر{% endif %}</div>

<div class="uk-width-2-5 uk-text-left goldC-text" >آدرس</div><div class="uk-width-3-5 uk-text-right whiteC-text">{{jewler.address}}</div>
  <div class="uk-width-1-1 uk-text-right whiteC-text"><a href="{% url 'commonuser:jewlerdeny' jewler.pk %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">رد درخواست</a></div>

      </div>
</div>
</div>
  {% endfor %}

    {% endblock %}

commonuser/templates/commonuser/profile.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
ورود | شعله خیز
</title>
{% endblock %}
{% block body_block %}
<div style="margin:8%" class=" uk-text-center ">

      <div class=" uk-block ">
<div class="uk-card uk-card-hover uk-card-body darkgreyC ">
    <h3 style="font-size:30px;" class="goldC-text uk-card-title uk-align-center fHarmattan">ناحیه کاربری</h3><br>
      <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>

      <div class="uk-width-3-5@m ">
        <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan goldC-text uk-text-large ">
        <div class="uk-text-left">
          شماره همراه
        </div>
          </div>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan whiteC-text uk-text-right uk-text-large">
        {{commonuser.user.username}}
          </div>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan goldC-text uk-text-large">
        <div class="uk-text-left">
          نام و نام خانوادگی
        </div>
          </div>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan whiteC-text uk-text-right uk-text-large">
        {{commonuser.user.name}}
          </div>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan goldC-text uk-text-large">
        <div class="uk-text-left">
          آدرس
        </div>
          </div>
          <div class="uk-width-1-2 uk-width-1-2@m fHarmattan whiteC-text uk-text-right uk-text-large">
        {{commonuser.address}}
          </div>
        </div>
      </div>

      <div class="uk-width-2-5@m">
        <a href="{% url 'commonuser:update' user.slug %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">ویرایش اطلاعات کاربری</a>
        <a href="{% url 'order:listforuser' user.slug %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">لیست سفارشات</a>
        <a href="{% url 'accounts:passwordchange' user.slug %}" class="uk-button goldC uk-width-1-1 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">تغییر رمز عبور</a>

      </div>

      </div>
      <br>
<br><br>
    </form>
</div>

</div>
</div>
<br><br><br>

{% endblock %}

commonuser/templates/commonuser/signup.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
ورود | شعله خیز
</title>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}
{% block body_block %}
<div   class="uk-text-center ">
  <div style="padding:10%">


<div style="padding: 3%;border-radius: 8px;" uk-grid>
  <div class=" uk-width-1-1 uk-block fHarmattan ">
<div class="uk-card uk-card-hover uk-card-body darkgreyC ">
    <h3 style="font-size:30px;" class="goldC-text uk-card-title uk-align-center fHarmattan">عضویت</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>

      <div class="uk-width-1-2@m">
{{user_form.username}}
      </div>

      <div class="uk-width-1-2@m">
      {{user_form.name}}
      </div>

      <div class="uk-width-1-2@m">
      {{user_form.password1}}
      </div>

      <div class="uk-width-1-2@m">
      {{user_form.password2}}
      </div>


      <div class="uk-width-1-2@m">
      <label style="padding-top:8px; white-space:pre" class="uk-text-right fHarmattan goldC-text">{{commonuser_form.is_jewler_request}}   طلا و جواهر فروش هستید؟ </label>
      </div>

      <div class="uk-width-1-2@m">
      <label style="padding-top:8px; white-space:pre" class="uk-text-right fHarmattan goldC-text">{{user_form.terms}}<a href="{% url 'company:termsandconditions' %}">   شرایط و قوانین</a> را خوانده و قبول دارم</label>
      </div>
      <div class="uk-width-1-1@m">
      {{commonuser_form.address}}
      </div>

              {% if user_form.errors or commonuser_form.errors %}
                  <div class="uk-width-1-1">
              <p  class="fHarmattan goldC-text">لطفا در وارد کردن فیلد ها دقت کنید.</p>
              <p  class="fHarmattan goldC-text">{{user_form.errors}}</p>
              <p  class="fHarmattan goldC-text">{{commonuser_form.errors}}</p>
              </div>
              {% endif %}

      </div>
      <br>
      <button style="margin-top:20px;" class="uk-button uk-button-primary fHarmattan goldC darkgreyC-text" type="submit">تایید
    </button><br><br>
    </form>
</div>

</div>
  </div>
</div>
<div class="uk-grid-match uk-text-center" uk-grid>


  <div class="uk-width-expand" style=" width:43%; border-top: solid #d4af37  1px;">

  </div>
  <div class="uk-align-center uk-width-1-5" style="margin-top:-20px;padding-left:30px;width:105px;" >
<i class="medium material-icons goldC-text" style="font-size: 45px;">fingerprint</i>
  </div>
  <div class="uk-width-expand" style="margin-left:-30px; width:43%; border-top: solid #d4af37 1px;" >

  </div>
</div>

<div class="uk-text-center">
  <h3 class="fHarmattan goldC-text">حساب کاربری دارید؟</h3>
    <a class="uk-button uk-button-large darkgreyC-text goldC fHarmattan uk-text-large" href="{% url 'accounts:login' %}">ورود</a>
  </div>
<br><br>
</div>
{% endblock %}
{% block script_block %}
<script type="text/javascript">
  function myFunction() {
  // Get the checkbox
  var checkBox = document.getElementById("myCheck");
  // Get the output text
  var text = document.getElementById("text");

  // If the checkbox is checked, display the output text
  if (checkBox.checked == true){
    text.style.display = "block";
  } else {
    text.style.display = "none";
  }
}
</script>
{% endblock %}

commonuser/templates/commonuser/update.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}
      {{user_form.as_p}}
      {{commonuser_form.address}}
      <input type="submit" name="" value="submit">
    </form>

  </body>
</html>