JewleryStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView, name='home'),
    path('masteruser/', include('masteruser.urls',namespace = 'masteruser')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('commonuser/', include('commonuser.urls',namespace = 'commonuser')),
    path('jewlery/', include('jewlery.urls',namespace = 'jewlery')),
    path('order/', include('order.urls',namespace = 'order')),
    path('company/', include('company.urls',namespace = 'company')),
    path('',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from accounts.forms import UserLoginForm
from accounts.views import (SuperUserDashboardView, PasswordChangeView,
                        ForgotPasswordView, WaitView, WrongPhoneNumberView)

# handmade
app_name ='accounts'
urlpatterns = [
    path('auth/',auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=UserLoginForm), name='login'),
    path('dashboard/<slug:slug>/',SuperUserDashboardView, name='dashboard'),
    path('wait/',WaitView, name='wait'),
    path('wrongphonenumber/',WrongPhoneNumberView, name='wrongphonenumber'),
    path('password-change/<slug:slug>/',PasswordChangeView, name='passwordchange'),
    path('password-forget/',ForgotPasswordView, name='passwordforget'),
]

commonuser/urls.py
from django.urls import include, path
from commonuser.views import (TwoMinWaitView, CommonUserSignupView, UserConfirmView,
                            CustomerListView, JewlerListView, JewlerReqListView,
                            JewlerConfirmView, JewlerDenyView, CommonUserProfileView,
                            CommonUserUpdateView)

# handmade
app_name ='commonuser'
urlpatterns = [
    path('signup/',CommonUserSignupView, name='signup'),
    path('confirm/',UserConfirmView, name='confirm'),
    path('wait/',TwoMinWaitView, name='twominwait'),
    path('customerlist/',CustomerListView, name='customerlist'),
    path('jewlerlist/',JewlerListView, name='jewlerlist'),
    path('jewlerreqlist/',JewlerReqListView, name='jewlerreqlist'),
    path('jewler-confirm/<int:pk>',JewlerConfirmView, name='jewlerconfirm'),
    path('jewler-deny/<int:pk>',JewlerDenyView, name='jewlerdeny'),
    path('profile/<slug:slug>',CommonUserProfileView, name='profile'),
    path('update/<slug:slug>',CommonUserUpdateView, name='update'),
]

company/urls.py
from django.urls import include, path
from company.views import (ContactUsView, AboutUsView, ContactUsListView,
                            ContactUsDeleteView, FAQsView, TermandConditionsView)

app_name ='company'
urlpatterns = [
    path('about-us/',AboutUsView, name = 'aboutus'),
    path('faqs/', FAQsView, name = 'faqs'),
    path('terms-and-conditions/',TermandConditionsView, name = 'termsandconditions'),
    path('contact-us/',ContactUsView, name = 'contactus'),
    path('contact-us-list/',ContactUsListView, name = 'contactuslist'),
    path('contact-us-delete/<int:pk>',ContactUsDeleteView, name = 'contact-us-delete'),

]

jewlery/urls.py
from django.urls import include, path
from jewlery.views import (JewleryCreateView,ConfirmedJewleryListView, JewleryDetailView,
                            JewleryUpdateView, JewleryPictureUpdateView, JewleryPictureAddView,
                            UnConfirmedJewleryListView, JewleryPublicListView, JewleryDeleteView,
                            JewleryPublicDetailView, CreateUnitView)

app_name = 'jewlery'
urlpatterns = [
    path('create-unit/', CreateUnitView, name='createunit'),
    path('create/', JewleryCreateView, name='create'),
    path('confirmed-list/', ConfirmedJewleryListView, name='confirmedlist'),
    path('unconfirmed-list/', UnConfirmedJewleryListView, name='unconfirmedlist'),
    path('public-list/', JewleryPublicListView, name='publiclist'),
    path('public-detail/<int:pk>/', JewleryPublicDetailView, name='publicdetail'),
    path('detail/<int:pk>/', JewleryDetailView, name='detail'),
    path('update/<int:pk>/', JewleryUpdateView, name='update'),
    path('delete/<int:pk>/', JewleryDeleteView, name='delete'),
    path('picture-update/<int:pk>/', JewleryPictureUpdateView, name='pictureupdate'),
    path('picture-add/<int:pk>/', JewleryPictureAddView, name='pictureadd'),

]

order/urls.py
from django.urls import include, path
from order.views import (OrderingView,OrderSuccessView, OrderListForJewleryView,
                        CheckedOrderListView, UnCheckedOrderListView, OrderListForCommonUserView,
                        CheckOrderView, UnCheckOrderView, OrderUpdateView, DeliverOrderView,
                        DeliveredOrderListView, UnDeliverOrderView, DeleteOrderView)

app_name = 'order'
urlpatterns = [
    path('ordering/<int:pk>/', OrderingView, name='ordering'),
    path('update/<int:pk>/', OrderUpdateView, name='update'),
    path('success/', OrderSuccessView, name='success'),
    path('list-for-jewlery/<int:pk>', OrderListForJewleryView, name='listforjewlery'),
    path('list-for-user/<slug:slug>', OrderListForCommonUserView, name='listforuser'),
    path('checked-list/', CheckedOrderListView, name='checkedlist'),
    path('unchecked-list/', UnCheckedOrderListView, name='uncheckedlist'),
    path('check/<int:pk>/', CheckOrderView, name='check'),
    path('uncheck/<int:pk>/', UnCheckOrderView, name='uncheck'),
    path('deliver/<int:pk>/', DeliverOrderView, name='deliver'),
    path('deliver/<int:pk>/', DeleteOrderView, name='delete'),
    path('undeliver/<int:pk>/', UnDeliverOrderView, name='undeliver'),
    path('delivered-list/', DeliveredOrderListView, name='deliveredlist'),


]

templates/BaseTemplates/base1.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" class="greyC">
  <head>
    {% block head_block %}
    {% endblock %}
    {% load static %}
    <!DOCTYPE html>
    <html lang="en" dir="ltr">
      <head>
        <meta charset="utf-8">
        <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="/media/Logo/Logo.png"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lateef&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lalezar&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Markazi+Text&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Harmattan&display=swap" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'css/uikit-rtl.css' %}" media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}"/>
        <script src="{% static 'js/uikit.min.js' %}" ></script>
        <script src="{% static 'js/uikit-icons.min.js' %}" ></script>
      </head>
      <body style="min-width: 100%; max-width:100%;  overflow-x: hidden;" class="greyC">
        <header>
            <nav class="uk-navbar-container" style="position: fixed;right: 0;left: 0;top: 0;z-index: 1030; background-color:#262626  ;box-shadow: 0 15px 17px rgba(0, 0,0, 0.18);" uk-navbar>



                <div class="uk-navbar-right">
<a href="#" class="uk-navbar-toggle uk-hidden@s goldC-text" uk-navbar-toggle-icon uk-toggle="target: #sidenav"></a>
                    <ul class="uk-navbar-nav uk-navbar-nav uk-visible@s">

                      {% if user.is_authenticated %}
                      <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"  href="{% url 'logout' %}">خروج</a></li>
                      {% else %}
                        <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'accounts:login' %}">ورود</a></li>
                        <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'commonuser:signup' %}">عضویت</a></li>
                        {% endif %}
                    <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'jewlery:publiclist' %}">محصولات</a></li>
                    {% if user.is_authenticated and user.is_superuser %}
                      <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"    href="{% url 'accounts:dashboard' user.slug %}">داشبورد</a></li>
                    {% endif %}
                    {% if user.is_authenticated and user.is_masteruser %}
                      <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'masteruser:dashboard' user.slug %}">داشبورد</a></li>
                    {% endif %}
                    {% if user.is_authenticated and user.is_commonuser %}
                    <li>
                      <a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="#">ناحیه کاربری</a>
                        <div class="uk-navbar-dropdown darkgreyC">
                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'commonuser:profile' user.slug %}">پروفایل</a></li>
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'order:listforuser' user.slug %}">سفارشات</a></li>                              </ul>
                        </div>
                    </li>

                    {% endif %}
                    <li>
                      <a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="#">زر مارکت</a>
                        <div class="uk-navbar-dropdown darkgreyC">
                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:aboutus' %}">درباره ما</a></li>
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:contactus' %}">تماس با ما</a></li>
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:faqs' %}">سوالات متداول</a></li>
                                <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:termsandconditions' %}">قوانین</a></li>
                              </ul>
                      </div>
                    </li>
                    </ul>

                </div>
                <div class="uk-navbar-left">

                    <ul class="uk-navbar-nav">
                        <li>
                          <a  class="uk-navbar-item uk-logo" href="{% url 'home' %}"><img style="margin:5px;" src="/media/Logo/Logo.png" width="80" alt=""></a>
                        </li>
                    </ul>

                </div>
            </nav>
        </header>

        <div id="sidenav" uk-offcanvas="flip: true" class="uk-offcanvas " style="z-index: 1031;">
            <div class="uk-offcanvas-bar">
                <ul class="uk-nav">

                          {% if user.is_authenticated %}
                          <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'logout' %}">خروج</a></li>
                          {% else %}
                            <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'accounts:login' %}">ورود</a></li>
                            <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'commonuser:signup' %}">عضویت</a></li>
                            {% endif %}
                        <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'jewlery:publiclist' %}">محصولات</a></li>
                        {% if user.is_authenticated and user.is_superuser %}
                          <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"    href="{% url 'accounts:dashboard' user.slug %}">داشبورد</a></li>
                        {% endif %}
                        {% if user.is_authenticated and user.is_masteruser %}
                          <li><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'masteruser:dashboard' user.slug %}">داشبورد</a></li>
                        {% endif %}
                        {% if user.is_authenticated and user.is_commonuser %}
                        <li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'commonuser:profile' user.slug %}">پروفایل</a></li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'order:listforuser' user.slug %}">سفارشات</a></li>
                        </li>

                        {% endif %}
                        <li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:aboutus' %}">درباره ما</a></li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:contactus' %}">تماس با ما</a></li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:faqs' %}">سوالات متداول</a></li>
                          <li class="uk-active"><a style="color:#c7a046; font-family: 'Harmattan', sans-serif; font-size:20px;"   href="{% url 'company:termsandconditions' %}">قوانین</a></li>
                        </li>
                </ul>
            </div>
        </div>
<br><br><br><br><br>
      {% block body_block %}
      {% endblock %}
      <br>
<footer class="darkgreyC" style="padding:50px;">
<div  class="uk-grid uk-grid-small uk-child-width-1-3 fHarmattan" uk-grid>
  <div class="uk-text-">
<a href="#" class="goldC-text">درباره ما</a><br>
<a href="#" class="goldC-text">تماس با ما</a><br>
<a href="#" class="goldC-text">وبلاگ</a><br>
<a href="#" class="goldC-text">سوالات متداول</a><br>
  </div>
  <div class="uk-text-=">
    <a href="#" class="goldC-text">لیست طلا و جواهرات</a><br>
    <a href="#" class="goldC-text">عضویت</a><br>
  {% if user.is_authenticated %}
    <a href="#" class="goldC-text">خروج</a><br>
  {% else %}
    <a href="#" class="goldC-text">ورود</a><br>
    {% endif %}
  </div>
  <div class="uk-text-center">
    <a href="#" class="goldC-text"> <img width="35" src="/media/Logo/telegram.png" alt=""></a><br>
    <a href="#" class="goldC-text"><img width="35" src="/media/Logo/instagram.png" alt=""></a><br>

  </div>
</div>
<div style="margin-top:20px;" class="fHarmattan milkywhite-text uk-text-right">
  <span class="uk-text-right">
      آدرس: تبریز - بازار امیر
  </span>
  <span class="uk-text-left">
شماره تماس: 09368361943
  </span>
</div>


</footer>
      {% block script_block %}
      {% endblock %}
    </body>
  </html>

templates/BaseTemplates/emptybase.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %} 

    {% endblock %}




<!-- ################## form ############## -->


{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
ورود | شعله خیز
</title>
{% endblock %}
{% block body_block %}
<br>
<div class="uk-grid-match uk-grid-small uk-text-center " uk-grid>
  <div class="uk-width-1-6 uk-width-1-4@m">

  </div>
      <div class="uk-width-2-3 uk-width-1-2@m uk-block ">
<div class="uk-card uk-card-hover uk-card-body darkgreyC ">
    <h3 style="font-size:30px;" class="goldC-text uk-card-title uk-align-center fHarmattan">تماس با ما</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>

      <div class="uk-width-1-2@m">
      {{form.name}}
      </div>

      <div class="uk-width-1-2@m">
      {{form.phone_number}}
      </div>
      <div class="uk-width-1-1@m">
      {{form.request}}
      </div>


              {% if form.errors %}
                  <div class="uk-width-1-1">
              <p  class="fHarmattan goldC-text">مشکلی پیش آمد. لطفا دوباره سعی کنید</p>
              </div>
              {% endif %}

      </div>
      <br>
      <button style="margin-top:20px;" class="uk-button uk-button-primary fHarmattan goldC darkgreyC-text" type="submit">تایید
    </button><br><br>
    </form>
</div>
<div class="uk-width-1-6 uk-width-1-4@m">

</div>
</div>
</div>
<br><br><br>

{% endblock %}