JewleryStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView, name='home'),
    path('masteruser/', include('masteruser.urls',namespace = 'masteruser')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('commonuser/', include('commonuser.urls',namespace = 'commonuser')),
    path('jewlery/', include('jewlery.urls',namespace = 'jewlery')),
    path('order/', include('order.urls',namespace = 'order')),
    path('company/', include('company.urls',namespace = 'company')),
    path('',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/urls.py
from django.urls import include, path
from order.views import (OrderingView,OrderSuccessView, OrderListForJewleryView,
                        CheckedOrderListView, UnCheckedOrderListView, OrderListForCommonUserView,
                        CheckOrderView, UnCheckOrderView, OrderUpdateView, DeliverOrderView,
                        DeliveredOrderListView, UnDeliverOrderView, DeleteOrderView)

app_name = 'order'
urlpatterns = [
    path('ordering/<int:pk>/', OrderingView, name='ordering'),
    path('update/<int:pk>/', OrderUpdateView, name='update'),
    path('success/', OrderSuccessView, name='success'),
    path('list-for-jewlery/<int:pk>', OrderListForJewleryView, name='listforjewlery'),
    path('list-for-user/<slug:slug>', OrderListForCommonUserView, name='listforuser'),
    path('checked-list/', CheckedOrderListView, name='checkedlist'),
    path('unchecked-list/', UnCheckedOrderListView, name='uncheckedlist'),
    path('check/<int:pk>/', CheckOrderView, name='check'),
    path('uncheck/<int:pk>/', UnCheckOrderView, name='uncheck'),
    path('deliver/<int:pk>/', DeliverOrderView, name='deliver'),
    path('deliver/<int:pk>/', DeleteOrderView, name='delete'),
    path('undeliver/<int:pk>/', UnDeliverOrderView, name='undeliver'),
    path('delivered-list/', DeliveredOrderListView, name='deliveredlist'),


]

order/models.py
from django.db import models
import jdatetime
from django_jalali.db import models as jmodels
from commonuser.models import CommonUserModel
from jewlery.models import JewleryModel


class OrderModel(models.Model):
    jewlery = models.ForeignKey(JewleryModel, on_delete = models.CASCADE,
                                  related_name = 'orders')
    commonuser = models.ForeignKey(CommonUserModel, on_delete = models.CASCADE,
                                  related_name = 'orders')
    description = models.TextField(null = True, blank = True)
    is_checked = models.BooleanField(null = False, default = False)
    is_delivered = models.BooleanField(null = False, default = False)
    numbers = models.IntegerField(null = True, blank = True)
    weight = models.FloatField(null = True, blank = True)
    sale_wage = models.FloatField(null = True, blank = True)
    jdatetime = jmodels.jDateTimeField(null = False,default = jdatetime.datetime.now())
    check_datetime = jmodels.jDateTimeField(null = True, blank = True)
    price = models.IntegerField(null = False, blank = False)
    unit = models.IntegerField(null = False, blank = False)
    name = models.CharField(max_length = 264, null = True, blank = True)
    phone_number = models.IntegerField(null = True, blank = True)
    address = models.TextField(null = True, blank = True)

order/forms.py
from django import forms
from order.models import OrderModel

class OrderForm(forms.ModelForm):
    class Meta():
        model = OrderModel
        fields = ('description','weight','numbers','name','address','phone_number',)
        widgets = {
        'name': forms.TextInput(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-input fHarmattan','id':'name'},),
        'description': forms.Textarea(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-textarea fHarmattan','rows':'3',},),
        'phone_number': forms.TextInput(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-input fHarmattan',},),
        'numbers': forms.NumberInput(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-input fHarmattan',},),
        'weight': forms.NumberInput(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-input fHarmattan',},),
        'address': forms.Textarea(attrs={'style':'color:#c7a046;background-color:#212121;','class':'uk-textarea fHarmattan','rows':'3','required':'true'},),
}

order/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
import jdatetime
from django.conf import settings
from django.utils import timezone

#handmade
from order.models import OrderModel
from order.forms import OrderForm
from commonuser.models import CommonUserModel
from accounts.models import UserModel
from jewlery.models import JewleryModel, UnitModel
from commonuser.decorators import commonuser_required, jewler_required
from masteruser.decorators import masteruser_required


@login_required
@commonuser_required
def OrderingView(request, pk):

    jewlery = get_object_or_404(JewleryModel, pk=pk)
    commonuser = get_object_or_404(CommonUserModel,user=request.user)
    unit = UnitModel.objects.latest('jdatetime')
    ### Calculate Price
    sale_weight = (jewlery.weight + jewlery.weight * jewlery.sale_wage/100) * jewlery.karat / 750
    price = (unit.unit/4.3317) * sale_weight / 10000
    price = int(price) + 1
    price = price * 10000
    ###
    if request.method == 'POST':
        order_form = OrderForm(data = request.POST)
        if order_form.is_valid():
             order = order_form.save(commit = False)
             order.commonuser = commonuser
             order.jewlery = jewlery
             order.price = price
             order.sale_wage = jewlery.sale_wage
             order.unit = unit.unit
             order.save()
             return HttpResponseRedirect(reverse('order:success'))
        else:
             print(order_form.errors)

    else:
        order_form = OrderForm()
        order_form.fields['name'].widget.attrs['value'] = request.user.name
        order_form.fields['phone_number'].widget.attrs['value'] = request.user.username
        order_form.fields['numbers'].widget.attrs['value'] = 1
    return render(request,'order/ordering.html',
                          {'form':order_form,'jewlery':jewlery})


def OrderSuccessView(request):
    return render(request,'order/success.html')


@login_required
@masteruser_required
def OrderListForJewleryView(request, pk):
    jewlery = JewleryModel.objects.get(pk = pk)
    orders = OrderModel.objects.filter(jewlery = jewlery)
    return render (request,'order/listforjewlery.html',{'orders':orders})


@login_required
@commonuser_required
def OrderListForCommonUserView(request, slug):
    user = UserModel.objects.get(slug = slug)
    commonuser = CommonUserModel.objects.get(user = user)
    orders = OrderModel.objects.filter(commonuser = commonuser)
    return render (request,'order/listforcommonuser.html',{'orders':orders})


@login_required
@masteruser_required
def CheckedOrderListView(request):
    orders = OrderModel.objects.filter(is_checked = True)
    return render (request,'order/checkedlist.html',{'orders':orders})


@login_required
@masteruser_required
def UnCheckedOrderListView(request):
    orders = OrderModel.objects.filter(is_checked = False)
    return render (request,'order/uncheckedlist.html',{'orders':orders})


@login_required
@masteruser_required
def CheckOrderView(request, pk):
    order = OrderModel.objects.get(pk = pk)
    order.is_checked = True
    order.save()
    return HttpResponseRedirect(reverse('order:uncheckedlist'))


@login_required
@masteruser_required
def DeleteOrderView(request, pk):
    order = OrderModel.objects.get(pk = pk)
    order.delete()
    return HttpResponseRedirect(reverse('order:uncheckedlist'))


@login_required
@masteruser_required
def UnCheckOrderView(request, pk):
    order = OrderModel.objects.get(pk = pk)
    order.is_checked = False
    order.save()
    return HttpResponseRedirect(reverse('order:checkedlist'))


@login_required
@masteruser_required
def DeliverOrderView(request, pk):
    order = OrderModel.objects.get(pk = pk)
    order.is_delivered = True
    order.save()
    return HttpResponseRedirect(reverse('order:checkedlist'))


@login_required
@masteruser_required
def UnDeliverOrderView(request, pk):
    order = OrderModel.objects.get(pk = pk)
    order.is_delivered = False
    order.save()
    return HttpResponseRedirect(reverse('order:deliveredlist'))


@login_required
@masteruser_required
def DeliveredOrderListView(request):
    orders = OrderModel.objects.filter(is_delivered = True)
    return render (request,'order/deliveredlist.html',{'orders':orders})


@login_required
@jewler_required
def OrderUpdateView(request,pk):
    order = get_object_or_404(OrderModel, pk = pk)
    if order.commonuser == request.user.commonusers:
        order_update_form = OrderForm(request.POST or None, instance = order)
        if order_update_form.is_valid():
            order_update_form.save()
            order.save()
            return HttpResponseRedirect(reverse('order:listforcommonuser'))
        return render(request,'order/update.html',
                              {'form':order_update_form,
                              'order':order,})

order/templates/order/checkedlist.html
{% extends "BaseTemplates/base1.html" %}
{% load customtags %}


{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<div  class="uk-text-center ">
  <div class="fHarmattan goldC-text">
    سفارشات چک شده
  </div>
  {% for order in orders %}
<div style="margin:5%; padding: 3%;border-radius: 8px;" class="uk-card uk-card-large darkgreyC" uk-grid>

  <div class=" uk-width-2-5@s uk-width-1-1 uk-block fHarmattan ">
    <div style=" border-radius:20px; margin-top:30px" class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1" uk-slider="center: true">

        <ul  class="uk-slider-items uk-grid" uk-lightbox="animation: slide">
          {% for pic in order.jewlery.pictures.all %}
            <li class="uk-width-3-4">
                <a class="uk-panel uk-inline" href="{{pic.picture.url}}">
                    <img width="2000" height="2000" src="{{pic.picture.url}}" alt="">

                </a>
            </li>
            {% endfor %}
        </ul>

        <a style="color:#d4af37" class="uk-position-center-left uk-position-small uk-hidden-hover goldC-text" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
        <a style="color:#d4af37" class="uk-position-center-right uk-position-small uk-hidden-hover goldC-text" href="#" uk-slidenav-next uk-slider-item="next"></a>

    </div>
  </div>
<div class="uk-width-3-5@s uk-width-1-1 fHarmattan uk-text-left goldC-text" uk-grid>
  <div style="margin-top:30px;margin-right:20px; border-bottom:1px solid #d4af37" class="uk-width-1-1 fHarmattan goldC-text uk-text-center uk-text-bold">
مشخصات طلا
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
نام
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.name}}
  </div>
  <div class=" uk-width-1-4 fHarmattan ">دسته بندی</div>
   <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {% if order.jewlery.is_goldset %}  سرویس طلا{% endif %}
  {% if order.jewlery.is_pendant %} مدال {% endif %}
  {% if order.jewlery.is_bracelet %} دستبند {% endif %}
  {% if order.jewlery.is_necklace %} گردنبند {% endif %}
  {% if order.jewlery.is_bangle %} النگو {% endif %}
  {% if order.jewlery.is_chain %} زنجیر {% endif %}
  {% if order.jewlery.is_earings %} گوشواره {% endif %}
  {% if order.jewlery.is_halfset %} نیم ست {% endif %}
  {% if order.jewlery.is_watch %} ساعت {% endif %}
  {% if order.jewlery.is_anklet %} پابند {% endif %}
   </div>
  <div class=" uk-width-1-4 fHarmattan ">
وزن
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.weight}}g
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
ساخت کشور
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.made_in}}
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
جنس
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{% if order.jewlery.is_unisex %}زنانه و مردانه{% else %}{% if order.jewlery.is_womanly %}زنانه{% else %}مردانه{% endif %}{% endif %}
  </div>

    <div class=" uk-width-1-4 fHarmattan ">
  نام سازنده
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.jewlery.company_name}}
    </div>
    <div class=" uk-width-1-4 fHarmattan ">
عیار
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.jewlery.karat}}
    </div>
    <div class=" uk-width-1-4 fHarmattan ">
اجرت
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.sale_wage}}%
    </div>

     <div class=" uk-width-1-1 fHarmattan uk-text-center">
       <div style="border:solid 1px #d4af37; border-radius:5px; font-size:18px;direction: ltr;"  class="">
         {{order.price|pricedashes}} R
       </div>

     </div>
  </div>
     <div style="margin-top:30px;margin-right:20px; border-bottom:1px solid #d4af37" class="uk-width-1-1 fHarmattan goldC-text uk-text-center uk-text-bold">
   مشخصات سفارش
     </div>

     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تاریخ سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.jdatetime.date}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
زمان سفارش
     </div>
     <div style="direction:ltr;" class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.jdatetime.time}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
هر مثقال طلا در زمان سفارش
     </div>
     <div style="direction:ltr;" class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.unit|pricedashes}} R
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تعداد سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.numbers}}
     </div>

     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تعداد سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.numbers}}
     </div>
     {% if order.commonuser.is_jewler %}
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
وزن سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.weight}}
 </div>{% endif %}
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
وضعیت سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
{% if order.is_delivered %}تحویل داده شده{% else %}{% if order.is_checked %}در حال ارسال{% endif %}در حال بررسی{% endif %}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
شماره تماس کاربر
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.commonuser.user.username}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
شماره تماس سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.phone_number}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
نام سفارش دهنده
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.commonuser.user.name}}
     </div>
     <div class=" uk-width-1-1 uk-width-1-1@s goldC-text fHarmattan ">

     </div>

     <div class=" uk-width-1-2 uk-width-1-3@s goldC-text fHarmattan ">
آدرس سفارش
     </div>
     <div class=" uk-width-1-2 uk-width-1-3@s fHarmattan uk-text-right whiteC-text">
   {{order.address}}
     </div>


     <div class=" uk-width-1-2 uk-width-1-3@s goldC-text fHarmattan ">
توضیحات سفارش
     </div>
     <div class=" uk-width-1-2 uk-width-1-3@s fHarmattan uk-text-right whiteC-text">
   {{order.description}}
     </div>



</div>
<a href="{% url 'order:uncheck' order.pk %}" class="uk-button goldC uk-width-1-3 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large"></a>انتقال به چک نشده ها
<a href="{% url 'order:delete' order.pk %}" class="uk-button redC uk-width-1-3 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">حذف</a>
<a href="{% url 'order:deliver' order.pk %}" class="uk-button goldC uk-width-1-3 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">تحویل داده شد</a>

{% endfor %}
</div>


    {% endblock %}

order/templates/order/uncheckedlist.html
{% extends "BaseTemplates/base1.html" %}
{% load customtags %}


{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز
</title>
{% endblock %}

{% block body_block %}
<div  class="uk-text-center ">
  <div class="fHarmattan goldC-text">
    سفارشات چک نشده
  </div>
  {% for order in orders %}
<div style="margin:5%; padding: 3%;border-radius: 8px;" class="uk-card uk-card-large darkgreyC" uk-grid>

  <div class=" uk-width-2-5@s uk-width-1-1 uk-block fHarmattan ">
    <div style=" border-radius:20px; margin-top:30px" class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1" uk-slider="center: true">

        <ul  class="uk-slider-items uk-grid" uk-lightbox="animation: slide">
          {% for pic in order.jewlery.pictures.all %}
            <li class="uk-width-3-4">
                <a class="uk-panel uk-inline" href="{{pic.picture.url}}">
                    <img width="2000" height="2000" src="{{pic.picture.url}}" alt="">

                </a>
            </li>
            {% endfor %}
        </ul>

        <a style="color:#d4af37" class="uk-position-center-left uk-position-small uk-hidden-hover goldC-text" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
        <a style="color:#d4af37" class="uk-position-center-right uk-position-small uk-hidden-hover goldC-text" href="#" uk-slidenav-next uk-slider-item="next"></a>

    </div>
  </div>
<div class="uk-width-3-5@s uk-width-1-1 fHarmattan uk-text-left goldC-text" uk-grid>
  <div style="margin-top:30px;margin-right:20px; border-bottom:1px solid #d4af37" class="uk-width-1-1 fHarmattan goldC-text uk-text-center uk-text-bold">
مشخصات طلا
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
نام
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.name}}
  </div>
  <div class=" uk-width-1-4 fHarmattan ">دسته بندی</div>
   <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {% if order.jewlery.is_goldset %}  سرویس طلا{% endif %}
  {% if order.jewlery.is_pendant %} مدال {% endif %}
  {% if order.jewlery.is_bracelet %} دستبند {% endif %}
  {% if order.jewlery.is_necklace %} گردنبند {% endif %}
  {% if order.jewlery.is_bangle %} النگو {% endif %}
  {% if order.jewlery.is_chain %} زنجیر {% endif %}
  {% if order.jewlery.is_earings %} گوشواره {% endif %}
  {% if order.jewlery.is_halfset %} نیم ست {% endif %}
  {% if order.jewlery.is_watch %} ساعت {% endif %}
  {% if order.jewlery.is_anklet %} پابند {% endif %}
   </div>
  <div class=" uk-width-1-4 fHarmattan ">
وزن
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.weight}}g
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
ساخت کشور
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{{order.jewlery.made_in}}
  </div>
  <div class=" uk-width-1-4 fHarmattan ">
جنس
  </div>
  <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
{% if order.jewlery.is_unisex %}زنانه و مردانه{% else %}{% if order.jewlery.is_womanly %}زنانه{% else %}مردانه{% endif %}{% endif %}
  </div>

    <div class=" uk-width-1-4 fHarmattan ">
  نام سازنده
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.jewlery.company_name}}
    </div>
    <div class=" uk-width-1-4 fHarmattan ">
عیار
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.jewlery.karat}}
    </div>
    <div class=" uk-width-1-4 fHarmattan ">
اجرت
    </div>
    <div class=" uk-width-1-4 fHarmattan uk-text-right whiteC-text">
  {{order.sale_wage}}%
    </div>

     <div class=" uk-width-1-1 fHarmattan uk-text-center">
       <div style="border:solid 1px #d4af37; border-radius:5px; font-size:18px;direction: ltr;"  class="">
         {{order.price|pricedashes}} R
       </div>

     </div>
  </div>
     <div style="margin-top:30px;margin-right:20px; border-bottom:1px solid #d4af37" class="uk-width-1-1 fHarmattan goldC-text uk-text-center uk-text-bold">
   مشخصات سفارش
     </div>

     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تاریخ سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.jdatetime.date}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
زمان سفارش
     </div>
     <div style="direction:ltr;" class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.jdatetime.time}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
هر مثقال طلا در زمان سفارش
     </div>
     <div style="direction:ltr;" class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.unit|pricedashes}} R
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تعداد سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.numbers}}
     </div>

     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
تعداد سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.numbers}}
     </div>
     {% if order.commonuser.is_jewler %}
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
وزن سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.weight}}
 </div>{% endif %}
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
وضعیت سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
{% if order.is_delivered %}تحویل داده شده{% else %}{% if order.is_checked %}در حال ارسال{% endif %}در حال بررسی{% endif %}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
شماره تماس کاربر
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.commonuser.user.username}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
شماره تماس سفارش
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.phone_number}}
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s goldC-text fHarmattan ">
نام سفارش دهنده
     </div>
     <div class=" uk-width-1-4 uk-width-1-6@s fHarmattan uk-text-right whiteC-text">
   {{order.commonuser.user.name}}
     </div>
     <div class=" uk-width-1-1 uk-width-1-1@s goldC-text fHarmattan ">

     </div>

     <div class=" uk-width-1-2 uk-width-1-3@s goldC-text fHarmattan ">
آدرس سفارش
     </div>
     <div class=" uk-width-1-2 uk-width-1-3@s fHarmattan uk-text-right whiteC-text">
   {{order.address}}
     </div>


     <div class=" uk-width-1-2 uk-width-1-3@s goldC-text fHarmattan ">
توضیحات سفارش
     </div>
     <div class=" uk-width-1-2 uk-width-1-3@s fHarmattan uk-text-right whiteC-text">
   {{order.description}}
     </div>



</div>
<a href="{% url 'order:check' order.pk %}" class="uk-button goldC uk-width-1-3 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">چک کردن</a>
<a href="{% url 'order:delete' order.pk %}" class="uk-button redC uk-width-1-3 uk-margin-small-bottom darkgreyC-text fHarmattan uk-text-large">حذف</a>

{% endfor %}
</div>


    {% endblock %}